// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package client

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// GetSharesResponse is returned by GetShares on success.
type GetSharesResponse struct {
	Shares []GetSharesSharesShare `json:"shares"`
}

// GetShares returns GetSharesResponse.Shares, and is useful for accessing the field via an interface.
func (v *GetSharesResponse) GetShares() []GetSharesSharesShare { return v.Shares }

// GetSharesSharesShare includes the requested fields of the GraphQL type Share.
type GetSharesSharesShare struct {
	// Display name
	Name string `json:"name"`
	// (KB) Free space
	Free int64 `json:"free"`
	// (KB) Used Size
	Used int64 `json:"used"`
	// (KB) Total size
	Size int64 `json:"size"`
	// Disks that are included in this share
	Include []string `json:"include"`
	// Disks that are excluded from this share
	Exclude []string `json:"exclude"`
	// Is this share cached
	Cache bool `json:"cache"`
	// Original name
	NameOrig string `json:"nameOrig"`
	// User comment
	Comment string `json:"comment"`
	// Allocator
	Allocator string `json:"allocator"`
	// Split level
	SplitLevel string `json:"splitLevel"`
	// Floor
	Floor string `json:"floor"`
	// COW
	Cow string `json:"cow"`
	// Color
	Color string `json:"color"`
	// LUKS status
	LuksStatus string `json:"luksStatus"`
}

// GetName returns GetSharesSharesShare.Name, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetName() string { return v.Name }

// GetFree returns GetSharesSharesShare.Free, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetFree() int64 { return v.Free }

// GetUsed returns GetSharesSharesShare.Used, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetUsed() int64 { return v.Used }

// GetSize returns GetSharesSharesShare.Size, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetSize() int64 { return v.Size }

// GetInclude returns GetSharesSharesShare.Include, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetInclude() []string { return v.Include }

// GetExclude returns GetSharesSharesShare.Exclude, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetExclude() []string { return v.Exclude }

// GetCache returns GetSharesSharesShare.Cache, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetCache() bool { return v.Cache }

// GetNameOrig returns GetSharesSharesShare.NameOrig, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetNameOrig() string { return v.NameOrig }

// GetComment returns GetSharesSharesShare.Comment, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetComment() string { return v.Comment }

// GetAllocator returns GetSharesSharesShare.Allocator, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetAllocator() string { return v.Allocator }

// GetSplitLevel returns GetSharesSharesShare.SplitLevel, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetSplitLevel() string { return v.SplitLevel }

// GetFloor returns GetSharesSharesShare.Floor, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetFloor() string { return v.Floor }

// GetCow returns GetSharesSharesShare.Cow, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetCow() string { return v.Cow }

// GetColor returns GetSharesSharesShare.Color, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetColor() string { return v.Color }

// GetLuksStatus returns GetSharesSharesShare.LuksStatus, and is useful for accessing the field via an interface.
func (v *GetSharesSharesShare) GetLuksStatus() string { return v.LuksStatus }

// GetVersionInfo includes the requested fields of the GraphQL type Info.
type GetVersionInfo struct {
	// Software versions
	Versions GetVersionInfoVersions `json:"versions"`
}

// GetVersions returns GetVersionInfo.Versions, and is useful for accessing the field via an interface.
func (v *GetVersionInfo) GetVersions() GetVersionInfoVersions { return v.Versions }

// GetVersionInfoVersions includes the requested fields of the GraphQL type InfoVersions.
type GetVersionInfoVersions struct {
	// Core system versions
	Core GetVersionInfoVersionsCoreCoreVersions `json:"core"`
}

// GetCore returns GetVersionInfoVersions.Core, and is useful for accessing the field via an interface.
func (v *GetVersionInfoVersions) GetCore() GetVersionInfoVersionsCoreCoreVersions { return v.Core }

// GetVersionInfoVersionsCoreCoreVersions includes the requested fields of the GraphQL type CoreVersions.
type GetVersionInfoVersionsCoreCoreVersions struct {
	// Unraid version
	Unraid string `json:"unraid"`
	// Unraid API version
	Api string `json:"api"`
	// Kernel version
	Kernel string `json:"kernel"`
}

// GetUnraid returns GetVersionInfoVersionsCoreCoreVersions.Unraid, and is useful for accessing the field via an interface.
func (v *GetVersionInfoVersionsCoreCoreVersions) GetUnraid() string { return v.Unraid }

// GetApi returns GetVersionInfoVersionsCoreCoreVersions.Api, and is useful for accessing the field via an interface.
func (v *GetVersionInfoVersionsCoreCoreVersions) GetApi() string { return v.Api }

// GetKernel returns GetVersionInfoVersionsCoreCoreVersions.Kernel, and is useful for accessing the field via an interface.
func (v *GetVersionInfoVersionsCoreCoreVersions) GetKernel() string { return v.Kernel }

// GetVersionResponse is returned by GetVersion on success.
type GetVersionResponse struct {
	Info GetVersionInfo `json:"info"`
}

// GetInfo returns GetVersionResponse.Info, and is useful for accessing the field via an interface.
func (v *GetVersionResponse) GetInfo() GetVersionInfo { return v.Info }

// The query executed by GetShares.
const GetShares_Operation = `
query GetShares {
	shares {
		name
		free
		used
		size
		include
		exclude
		cache
		nameOrig
		comment
		allocator
		splitLevel
		floor
		cow
		color
		luksStatus
	}
}
`

func GetShares(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetSharesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetShares",
		Query:  GetShares_Operation,
	}

	data_ = &GetSharesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetVersion.
const GetVersion_Operation = `
query GetVersion {
	info {
		versions {
			core {
				unraid
				api
				kernel
			}
		}
	}
}
`

func GetVersion(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetVersionResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetVersion",
		Query:  GetVersion_Operation,
	}

	data_ = &GetVersionResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
