// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package client

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// GetVersionInfo includes the requested fields of the GraphQL type Info.
type GetVersionInfo struct {
	// Software versions
	Versions GetVersionInfoVersions `json:"versions"`
}

// GetVersions returns GetVersionInfo.Versions, and is useful for accessing the field via an interface.
func (v *GetVersionInfo) GetVersions() GetVersionInfoVersions { return v.Versions }

// GetVersionInfoVersions includes the requested fields of the GraphQL type InfoVersions.
type GetVersionInfoVersions struct {
	// Core system versions
	Core GetVersionInfoVersionsCoreCoreVersions `json:"core"`
}

// GetCore returns GetVersionInfoVersions.Core, and is useful for accessing the field via an interface.
func (v *GetVersionInfoVersions) GetCore() GetVersionInfoVersionsCoreCoreVersions { return v.Core }

// GetVersionInfoVersionsCoreCoreVersions includes the requested fields of the GraphQL type CoreVersions.
type GetVersionInfoVersionsCoreCoreVersions struct {
	// Unraid version
	Unraid string `json:"unraid"`
	// Unraid API version
	Api string `json:"api"`
	// Kernel version
	Kernel string `json:"kernel"`
}

// GetUnraid returns GetVersionInfoVersionsCoreCoreVersions.Unraid, and is useful for accessing the field via an interface.
func (v *GetVersionInfoVersionsCoreCoreVersions) GetUnraid() string { return v.Unraid }

// GetApi returns GetVersionInfoVersionsCoreCoreVersions.Api, and is useful for accessing the field via an interface.
func (v *GetVersionInfoVersionsCoreCoreVersions) GetApi() string { return v.Api }

// GetKernel returns GetVersionInfoVersionsCoreCoreVersions.Kernel, and is useful for accessing the field via an interface.
func (v *GetVersionInfoVersionsCoreCoreVersions) GetKernel() string { return v.Kernel }

// GetVersionResponse is returned by GetVersion on success.
type GetVersionResponse struct {
	Info GetVersionInfo `json:"info"`
}

// GetInfo returns GetVersionResponse.Info, and is useful for accessing the field via an interface.
func (v *GetVersionResponse) GetInfo() GetVersionInfo { return v.Info }

// The query executed by GetVersion.
const GetVersion_Operation = `
query GetVersion {
	info {
		versions {
			core {
				unraid
				api
				kernel
			}
		}
	}
}
`

func GetVersion(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetVersionResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetVersion",
		Query:  GetVersion_Operation,
	}

	data_ = &GetVersionResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
